[build]
builder = "nixpacks"
installCommand = "npm install"

[deploy]
startCommand = "npx prisma migrate deploy && node .next/standalone/server.js"
healthcheckPath = "/"
restartPolicyType = "on_failure"
