[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npx prisma db push && node .next/standalone/server.js"
healthcheckPath = "/"
restartPolicyType = "on_failure"
